import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Tooltip from "rc-tooltip";
import useWindowSize from '@/hooks/WindowResize';
import Link from 'next/link';
import { useEffect, useState } from 'react';

enum screenSizes {
  big,
  medium,
  small
}

export default function Home() {
  const { windowSize } = useWindowSize();

  const [screenSize, setScreen] = useState<screenSizes>(screenSizes.big);
  // const [isMobile, setIsMobile] = useState<boolean>(false);

  useEffect(() => {
    if (windowSize.width > 1280) {
      setScreen(screenSizes.big);
    } else if (windowSize.width > 818) {
      setScreen(screenSizes.medium);
    } else {
      setScreen(screenSizes.small);
    }
  }, [windowSize])

  const isDisabled = true;

  return (
    <>
      <Head>
        <title>Smoove</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-screen w-screen relative bg-white overflow-hidden flex items-center justify-center">
        <div className='w-full h-full absolute  opacity-20 bg-center bg-cover bg-repeat-x '
          style={{
            backgroundImage: "url('/imgs/bg_clouds.png')",
            // transform: "translate(0px, -300px)"
          }}
        >
        </div>
        {/* <div className='w-full h-1/2 absolute bottom-0 bg-gradient-to-b from-transparent to-gray-500 opacity-30 z-20'></div> */}
        {/* Sun */}
        <div className='absolute left-0 top-[10%] w-full h-32 z-10'>
          <img src="/imgs/sun.webp" className='sun absolute h-48 top-0 left-52' />
        </div>
        {/* Clouds */}
        <div className='absolute left-[-2.5%] top-[10%] w-full h-32 z-10'>
          <img src="/imgs/cloud_1.png" className='cloud cloud1 absolute h-48 top-0 -left-24' />
          <img src="/imgs/cloud_1.png" className='cloud absolute h-48 top-12 left-4' />
        </div>
        {
          (screenSize == screenSizes.big) && (
            <div className='absolute right-[-2.5%] top-[12%] w-full h-32 z-10 '>
              <img src="/imgs/cloud_1.png" className='cloud cloud1 absolute h-48 top-0 right-10' />
              <img src="/imgs/cloud_1.png" className='cloud absolute h-48 top-12 right-24' />
            </div>
          )
        }
        {/* title */}
        <div className=' flex justify-center items-center flex-col z-20 relative p-[7.5%]' >
          {screenSize != screenSizes.big ? (
            <div className='font-arcade_gamer text-black text-center ' style={{
              textShadow: "rgb(104, 136, 255) 3px 3px 0px"
            }}>
              <h1 className='  text-6xl z-auto'>SMOOVE</h1>
              <h2 className=' text-3xl z-auto'>FINANCE</h2>
            </div>
          ) : (

            <div className='font-arcade_gamer text-black text-center ' style={{
              textShadow: "rgb(104, 136, 255) 8.41439px 8.41439px 0px"
            }}>
              <h1 className='  text-9xl z-auto'>SMOOVE</h1>
              <h2 className=' text-7xl z-auto'>FINANCE</h2>
            </div>
          )}
          {/* rgb(85, 100, 88) */}
          {/* my-12 */}
          <div className={` relative font-mon italic font-bold text-center text-GREY2 ${screenSize != screenSizes.big ? " text-xl " : " text-3xl "}  my-[1.5%]`}>Yields so good, like you milkin' it. </div>
          <div className={` relative flex justify-center items-center flex-col ${screenSize != screenSizes.big ? " text-xl " : " text-3xl "} `}>
            <Tooltip overlayInnerStyle={{
              backgroundColor: "white",
              borderRadius: "64px",
              color: "#444",
              borderColor: "white",
              fontFamily: "Montserrat",
              fontStyle: "italic",
              // fontWeight: "bold"
            }} placement="right" overlay={<span> Coming Soon! </span>}>
              <button className={`relative rounded-full block p-4 my-4 font-arcade_gamer bg-GREEN1 text-GREEN2 ${isDisabled ? "brightness-95 cursor-not-allowed" : ""} `}>
                LIQUID STAKING
              </button>
            </Tooltip>

            <Tooltip overlayInnerStyle={{
              backgroundColor: "white",
              borderRadius: "64px",
              color: "#444",
              borderColor: "white",
              fontFamily: "Montserrat",
              fontStyle: "italic",
              // fontWeight: "bold"
            }} placement="right" overlay={<span> Coming Soon! </span>}>
              <button className={`relative rounded-full block p-4 my-4 font-arcade_gamer bg-GREY1 text-GREY2 ${isDisabled ? "brightness-95 cursor-not-allowed" : ""}`} >
                DEFI VAULTS
              </button>
            </Tooltip>
          </div>
        </div>
        <div className='absolute left-0 bottom-0 w-full h-32 z-10'>


          {/* <div className='w-full h-full absolute bottom-0 bg-gradient-to-b from-transparent to-gray-800 opacity-50 z-20'></div> */}
          <div className='grass-plane h-16 w-full relative z-10'>
            {screenSize != screenSizes.small && (
              <>
                <div className='absolute  w-full -bottom-2 left-[10%]'>
                  {/* left-40 */}
                  <img src="/imgs/tree_1.webp" className='tree tree1 absolute h-48 -bottom-2 left-0 '
                    style={{
                      // transform:"translate(-80% ,0px)"
                    }}
                  />
                  {/* left-36 */}
                  <img src="/imgs/tree_2.webp" className='tree tree2 absolute h-72 -bottom-2 -left-6'
                    style={{
                      // transform:"translate(-80% ,0px)"
                    }}
                  />
                  {/* left-60 */}
                  <img src="/imgs/tree_1.webp" className='tree tree3 absolute h-52 -bottom-2 left-20'
                    style={{
                      // transform:"translate(-80% ,0px)"
                    }}
                  />
                </div>
                {/* right-40 */}
                <img src="/imgs/cool_cow_w.png" className='absolute h-48 bottom-0 right-[10%] animate-bounce'
                  style={{
                    // transform:"translate(-80% ,0px)"
                  }}
                />
              </>
            )}
            {/* footer */}
            <div className=' absolute bottom-[15%] w-full z-10'>
              <div className='w-full'>
                <div className=' flex items-center justify-center h-16 z-20'>
                  <Link href={"https://twitter.com/smoovefinance"} target="_blank" rel="noopener noreferrer"
                    className="h-full"
                  >
                    <button className='h-full'>
                      <img className="h-full" src="/icons/twitter.svg" />
                    </button>
                  </Link>

                  <button className='h-full mx-4 bg-black rounded-lg p-3'>
                    <img className="h-full" src="/icons/icon_discord.svg" />
                  </button>
                  <Link href="https://smoove.gitbook.io/smoove-docs/" target="_blank" rel="noopener noreferrer"
                    className="h-full"
                  >
                    <button className="h-full">
                      <img className="h-full rounded-lg" src="/icons/book.webp" />
                    </button>
                  </Link>
                </div>
                <div className={` font-bold text-lg font-mon  ${screenSize != screenSizes.big ? "text-gray-900" : "text-GREY2"} italic text-center drop-shadow`}>admin@smoove.finance</div>
              </div>
            </div>
          </div>
          <div className='ground-plane w-full h-16 bg-repeat-x bg-contain z-0'
            style={{
              backgroundImage: "url('/imgs/grass_tile_block.webp')"
            }}
          ></div>
        </div>
      </div>
    </>
  )
}
